# Generated by Django 4.2 on 2023-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('dept', models.CharField(choices=[('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Planning', 'Planning'), ('Security', 'Security'), ('Engineering', 'Engineering')], max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
