# Generated by Django 4.2 on 2023-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('empid', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('SALES', 'SALES'), ('AI', 'AI'), ('ML', 'ML'), ('CS', 'CS')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
