# Generated by Django 4.1.2 on 2023-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               
                ('EmployeeId', models.CharField(max_length=255)),
                ('Employeename', models.CharField(max_length=255)),
                ('Salary', models.IntegerField()),
                ('companyname', models.CharField(max_length=255)),
            ],
        ),
    ]
