# Generated by Django 4.2 on 2023-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('employee_salary', models.IntegerField()),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
