# Generated by Django 4.2 on 2023-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_employees_delete_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_salary',
            field=models.CharField(max_length=50),
        ),
    ]
