# Generated by Django 4.2.1 on 2023-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_blog_author_alter_blog_blog_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
