# Generated by Django 4.2.1 on 2023-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_blog_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.DateTimeField(null=True, verbose_name='Realse Date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
