# Generated by Django 4.2.1 on 2023-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_blog_author_alter_blog_blog_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_time',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(default=None, max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='path',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.DateTimeField(default=None, verbose_name='Realse Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
