# Generated by Django 4.2.1 on 2023-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_blog_author_alter_blog_blog_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='recommended',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
