# Generated by Django 4.1.1 on 2022-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
