# Generated by Django 4.2.1 on 2023-05-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_blog_content_alter_students_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rcg',
            field=models.CharField(max_length=2000000, null=True),
        ),
    ]
